# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf58374c628b8290c95e4ee01545da60ed4ee86b340c1a39ebec945d1446dbe1d79cf88ddd463baa68481f47f5a0ba00e585d70ca02240cac49e2ef37d91588d

test:
  secret_key_base: df733a7de01bafdb5541b146f9b6c9083d3ff71afa8f99a9cd4570de5ca74112cb15438e5c6a9fd3ec769fa8a9396dc01a87b11d68025ed1a6ded0bac57119a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
